### ISSUE TITLE
Wrong equation for gyration radius in PIRS-701

### ISSUE THREAD

**Issue by mainegra** [nrc-cnrc/EGSnrc#128]
Eq. `(4.11.14)` for the **gyroradius** should not contain a vector product as it is a scalar quantity.

**Comment by dworogers** [comment]
Interestingly, eqn 4.11.14 is in section 2.4.11 of the manual. Equation numbering is a bit strange, although in a brief look, I only found equations in Chapter 2 of the manual so that may be why equations are numbered by section rather than chapter.  This is not new. It was like this in the 2000 release.
