### ISSUE TITLE
ctcreate

### ISSUE THREAD

**Issue by yangguang222** [nrc-cnrc/EGSnrc#155]
Please:
In the terminal,  after choose ct formats and its slicenames, it displays :can not find that file or catalogue  ?

**Comment by rtownson** [comment]
Hi @yangguang222, please post questions about how to use EGSnrc in the [google+ community](https://plus.google.com/communities/106437507294474212197). We try to reserve github issues for bug reports! Thanks :)

**Comment by mainegra** [comment]
@yangguang222 this is not a help forum. It is meant for posting problems which should be fixed in EGSnrc. If you figure out that your problem is due to ctcreate and can provide enough proof we will look into it. If you require help using ctcreate, post your question in the [EGSnrc google++ community](https://plus.google.com/u/0/communities/106437507294474212197) where a you will find very a knowledgeable group of users than can help you. Alternatively, you can email any of the developers at the NRC.
