### ISSUE TITLE
Using egs_view on Wndows OS

### ISSUE THREAD

**Issue by Yass222** [nrc-cnrc/EGSnrc#158]
Hi everyone,
I am using EGS on Windows OS . I am trying to open my geometry + track with egs_view.
So I can view all examples from " EGSnrc -master \ EGSnrc -master \ HEN_HOUSE \ egs ++ \ geometry \ examples " but when i try to open " mygeom.egsinp " or " mygeom..egsgph " or " mygeom.egsgeom " I fails .
Can you help me.

I tried a Matlab program (EGS_WINDOWS). It have a strange display for CM SLABS. The program displays SLABS like two sheets with nothing between it. Moreover it doesn't display SLABS with square symmetry. 

Thanks

**Comment by rtownson** [comment]
Hi @Yass222, I see you already posted this question to our google group! Thanks, that is the appropriate place for this question (I recommend you also post your .egsinp file there). I will close this as an issue here, because it is not likely a bug with EGSnrc. You are welcome to post again if you have evidence it is in fact a bug.
