### ISSUE TITLE
dosxyznrc ::  number of regions > max allowed 

### ISSUE THREAD

**Issue by li-weihua** [nrc-cnrc/EGSnrc#159]
I want to define a phantom 30*30*30cm^3 with 300 regions in each dimension. The following error is
occurred, how to unset the max number of regions?

Input boundaries in the x-direction 
 ----------------------------------- 
 Initial boundary:       -15.000 
 Width in this group, number of regions in group:         0.100  300 
              ***ERROR: 
              number of regions > max allowed (  128)

**Comment by rtownson** [comment]
Hi @li-weihua, please post questions like this to the [EGSnrc google+ community](https://plus.google.com/communities/106437507294474212197). There is a very knowledgeable group of people there who can help (and we keep an eye on it)! This site is reserved for reporting problems which should be fixed in EGSnrc. If you discover that your problem is a bug and can provide evidence, we will look into it.

Having said that, look in $HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc_user_macros.mortan and increase IMAX, JMAX and KMAX (don't go too big, you need enough RAM). Then recompile dosxyznrc (and ctcreate if you use it?) using 'make clean; make'.
