### ISSUE TITLE
Lock files

### ISSUE THREAD

**Issue by crcrewso** [nrc-cnrc/EGSnrc#164]
Okay so I don't think this a bug, yet, but at the very least I think it's missing documentation. 

I've been running dosxyznrc on a new cluster (yay westgrid account) and I've noticed that the number of active jobs and the number of jobs in the lock file sometimes differ. I am assuming that this is because the jobs start too close to each other and they don't successfully increment the lock file. My Big question is what impact does this have on the validity of the 3ddose file and the run in general. The runs seem to start, execute and finalize without problems. My little question is, is there some way to fix it so the lock file does display the correct number of running jobs? Thank you.

**Comment by ftessier** [comment]
Indeed if a job starts and hangs for some reason then it might not increment (or decrement) the number of jobs in the lock file... What you describe typically happens indeed when too many jobs start concurrently and cause a race on the lock file. Try spacing out the launch of each job by a second or so. This has no effect on the validity of the results as far as I can imagine: all simulations run indenpendently and are combined at the end (automatically, or manually if needed).

**Comment by crcrewso** [comment]
@ftessier I wish I had the control to be able to do that. The way that this queue works is that when you submit to qsub, it hangs in limbo until a second scheduler can categorize it. I have some other issues with this scheduler (it starts jobs submitted out of order, like job 100 submitting 1 hour later might start before job 2) So adding a delay has no positive effects, unfortunately. 

What I'm worried about for recombination could be described as a race condition. Say I submit 10 jobs, but the lock file only shows 8. As I understand it, after the first 8 jobs close the last job will convert the pardoses to 3ddose files. But 2 simulations might still be running so any particles they grabbed would not be included. As such I'd be loosing 20% of my computations. Or is the last thread check more resilient then that?

**Comment by ftessier** [comment]
I see your point. I meant the result is valid in that the uncertainty reflects the actual number of histories that ran, irrespective of the number of jobs (or missing jobs). But as you say you might very well be missing a chunk of results and therefore not reached the desired accuracy. The lock file mechanism is unfortunately not very resilient, in fact it is rather fragile on large clusters. It will combine results when the number of jobs in the lock file reaches 0. One idea might be to increase your number of histories and add the `accuracy sought` key in your input file: then the simulation stops when it reaches the specified relative accuracy. The proper way to do this on a large cluster is to wrap the simulation in MPI so that the first jobs hands out history chunks to the other ones: doing away with lock files entirely.

**Comment by crcrewso** [comment]
Is that documented? I'd love to be using mpi for a myriad of reasons

**Comment by ftessier** [comment]
No, we have not implemented any MPI wrapper yet; and it is unlikely we would do so until the whole of EGSnrc is ported to C!!! But we ourselves routinely get bogged down with lock file problems, so at least the incentive is there.

**Comment by crcrewso** [comment]
I'd be happy to help but I only played around with threading on my own greenfield projects. I'm not quite sure where the wrapper should sit.
