### ISSUE TITLE
Cannot specify alternative C compiler in configuration script 

### ISSUE THREAD

**Issue by crcrewso** [nrc-cnrc/EGSnrc#176]
When running configure from `HEN_HOUSE/scripts`, I can select, say, gfortran4.9 (at least I think I can) and it will continue but fail to determine the version number. 

When I try to select gcc-4.8, or anything other than the generated list, the installer will not let me continue. 

I was hoping to be able to have a few config files each for a different compiler automatically generated using the installer but I will have to do so manually instead.

**Comment by ftessier** [comment]
The installer simply looks for common compiler executables by default, but otherwise **should** accept anything that is in your `$PATH`. Ensure that you have an executable called `gcc-4.8`, say, in your `$PATH`; this could be a symbolic link to the actual compiler binary, for example (an alias won't work because aliases are not passed down to scripts). If that still does not work, please comment and reopen this issue!

**Comment by crcrewso** [comment]
@ftessier I'm sure there must be a bug. I've installed the past gcc's using apt. When I type gcc-4.4, which is in my path, it won't go past the "Input the one you would like to use" line. I agree that while it should accept anything, it doesn't. This was tested on wsl and ubuntu. Is there something causing the dash or dot to break the parsing?

**Comment by ftessier** [comment]
I will look into it! Just to confirm, you can issue the `gcc-4.4` command in your terminal and it works as expected?

**Comment by crcrewso** [comment]
It does, I have also done the same tests for 4.6, 4.8, and 4.9.

**Comment by ftessier** [comment]
Ok you are right, the configuration script for the C compiler does not allow anything but what is in the list! I will update this and push as soon as possible. Good find! :1st_place_medal:

**Comment by crcrewso** [comment]
@ftessier I've looked at your travis config. If you can get this fixed I would like to update the travis script to test against multiple versions of gcc.

**Comment by Kawrakow** [comment]
The configure script does check that the input C compiler name is in the list. Originally it was the same with the Fortran compiler but I remember changing it at some point exactly because I wanted to be able to use non-standard compiler names. It would be a simple fix to repeat the logic used in the case of the Fortran compiler to the case of the C compiler. The configure script not "recognizing" the compiler is simply due to the fact that the logic is extremely simple: it just looks for g77 and gfortran and considers anything else to be unknown.

**Comment by mchamberland** [comment]
@ftessier  Has this been fixed? I'm running into the same problem. Fix would be very much appreciated (as my scripting skills are quite limited).

**Comment by mchamberland** [comment]
While I'm at it, any reason why the configuration name cannot include periods? For example, if I try calling it 'gcc4.8', the script spits back 'configuration name = gcc4'.

**Comment by crcrewso** [comment]
@mchamberland I remember this one when I was having problems testing against various gcc4.? versions. 

I'm curious are there other compilers that you are trying to use? I thought that all of the c/fortran compiler sets available were listed. As flang is not yet a thing in distros and the code still works with pgi I'm wondering what's left.

**Comment by mchamberland** [comment]
@crcrewso No, for now I'm sticking with gcc 4.8 because newer versions require updating too many dependencies on our system. But since I don't want to remove the old compiler (gcc 4.4), I created symlinks with the '-4.8' suffix, which the configure script is not picking up. My temporary workaround is just to explicitly add those names to the list that the configure script is checking.

**Comment by crcrewso** [comment]
Depending on your operating system gcc should automatically use gcc-4.8 Is that not the behaviour you're experiencing?

**Comment by mchamberland** [comment]
I mean, I get stuck in an infinite loop when specifying the gcc compiler to use in the configure script. 'gcc-4.8' does not show in the list and when I type 'gcc-4.8', it just loops back to asking me to input the compiler again.
