### ISSUE TITLE
The executlve program ’EGSnrc-configure-linux‘ does not work

### ISSUE THREAD

**Issue by ustc-czc** [nrc-cnrc/EGSnrc#19]

**Comment by kurijlj** [comment]
Same thing happens on Slackware 14.0 box.
Report from bash:
bash: ./EGSnrc-configure-linux: cannot execute binary file

**Comment by ftessier** [comment]
@kurijlj, did you `chmod +x EGSnrc-configure-linux`? If so, then perhaps you are trying to run on a 32-bit machine. The `EGSnrc-configure-linux` binary is a 64-bit executable.

**Comment by kurijlj** [comment]
That's it. I have 32-bit Slackware machine. So the question is will the rest of code work on such machine, and any chances of getting 32-bit binaries or source?

**Comment by ftessier** [comment]
The rest of the code should work fine because you compile it at your end. We provide precompiled binaries for some GUIs because they rely on Qt which is not usually installed by default. But if you have the Qt development files installed, you have all the source code to compile the GUIs as well. For example, go inside the `$HEN_HOUSE/gui` directory and issue the `make` command. We will consider adding 32-bit binaries based on demand.

**Comment by kurijlj** [comment]
Thank you. I will give it a try.

**Comment by ustc-czc** [comment]
Thank you! It works well on 64-bit ubuntu

2016-01-05 6:15 GMT+08:00 Frédéric Tessier <notifications@github.com>:
