### ISSUE TITLE
Update electron rest mass

### ISSUE THREAD

**Issue by ftessier** [nrc-cnrc/EGSnrc#22]
EGSnrc uses 511.0034 keV as the rest mass of the electron. But the accepted value is now 0.510 998 9461(31) MeV according to [CODATA 2014](http://physics.nist.gov/cgi-bin/cuu/Value?mec2mev). This is a change of only 0.0009%, but EGSnrc should nevertheless use the updated value. (Suggested by Dave Rogers).

There are about 60 instances of the hard coded 0.5110034 rest mass throughout the code:
`grep -R "0.511003" * | grep -v EX16MVp.egsgph | wc -l`

The hardcoded value for the rest mass in `examin` in two instances is set to 0.511003 instead of 0.5110034 (see https://github.com/nrc-cnrc/EGSnrc/blob/master/HEN_HOUSE/user_codes/examin/examin.mortran#L555)

**Comment by crcrewso** [comment]
This issue got me thinking (dangerous I know). While I used NIST a great deal for reference values I seem to remember that the particle data group is now the accepted source of oversight for subatomic masses. What does the group think about using the PGD citation instead of NIST?

http://pdglive.lbl.gov/Particle.action?node=S003

**Comment by mchamberland** [comment]
[PDG uses the CODATA dataset](http://pdg.lbl.gov/2015/reviews/rpp2015-rev-phys-constants.pdf) and actually cite CODATA/NIST. Problem solved!

**Comment by ftessier** [comment]
Thank you for the comments. Interesting!

**Comment by crcrewso** [comment]
That was a rabbit hole! I didn't even know about CODATA.

**Comment by rtownson** [comment]
Fixed in release-2017
