### ISSUE TITLE
No mention of qmake in the install directions 

### ISSUE THREAD

**Issue by crcrewso** [nrc-cnrc/EGSnrc#227]
I know this is a minor issue but could you please update the webpage when you have a chance, qmake is required for the egs_gui to compile but it is not listed in [https://github.com/nrc-cnrc/EGSnrc/wiki/install-EGSnrc-on-linux](url) 

Also a bookkeeping question, when will develop catch up to release-2017?

Thank you

**Comment by ftessier** [comment]
Thank you @crcrewso for the suggestion. The instructions for building the GUIs are on https://github.com/nrc-cnrc/EGSnrc/wiki/Building-GUIs-on-Linux (`qmake` comes with qt4-dev-tools). We want to keep instructions for compiling GUIs separate from installation, because most users prefer to download pre-compiled GUIs. However we could add a link to GUI build instructions from the installation page.

The `develop` branch will catchup to `release-2017` imminently, when we finish testing and cleaning up the latter. It will then be merged into `master` and tagged as release v2017. We are working on this right now, almost done!

**Comment by crcrewso** [comment]
@ftessier that mostly makes sense. I went looking for where to download the gui's and the only one I could find is the configure gui (which does let you build the rest of them of course) but wouldn't it require QT to run? I don't see QT mentioned on either the download page or the wiki linux install page. 

This release is starting to look like a lot of my wishlist has been crossed off. Great work!!!

**Comment by ftessier** [comment]
The pre-compiled GUIs we distribute are compiled statically, so they don't require a Qt installation; for exactly that reason!

**Comment by crcrewso** [comment]
I think I get my confusion now. The complied guis are all rolled into the installer. Which would explain why we don't need qmake to run the installer and why I was having so much trouble compiling them independently. 

This is definitely a PBKC moment, please close and forgive?

**Comment by ftessier** [comment]
Ok, chalking this one down in the PEBKAC column then! :-) But we ought to to clarify this in the instructions. Thanks!

**Comment by crcrewso** [comment]
Okay so I finally got it to compile but I don't know where the executable went (on me) and I had to create a linux64.conf (I only had linux.conf)
