### ISSUE TITLE
Cone stack geometry errors when inscribed in cylindrical geometry

### ISSUE THREAD

**Issue by mchamberland** [nrc-cnrc/EGSnrc#28]
Cone stack geometries throw geometry errors (of the type `howfar: called from the outside`) when they are inscribed in a base geometry which is cylindrical in shape. The frequency of errors seem to increase when the base geometry has radii that are similar to or smaller than the radii of the cone stack.

I've attached a simple input file below. It can be run in `tutor7pp` with the `tutor_data` PEGS file. In particular, check out what happens with the following cylinder radii in the phantom geometry:

radii = 0.25, 5.
radii = 0.5, 5. (perfect overlap between lower cone stack layer boundary and inner radius of cylinder)
radii = 0.75, 5.
radii = 1., 5. (perfect overlap between top cone stack layer boundary and inner radius of cylinder)
radii = 1.1, 5. (both cylinder radii larger than any cone stack layer radii)
radii = 1.2, 5.
radii = 5.

The issue seems to require at least 2 layers in the cone stack.

[conestack_geom_errors.txt](https://github.com/nrc-cnrc/EGSnrc/files/89817/conestack_geom_errors.txt)

**Comment by ftessier** [comment]
Whenever there are mathematically overlapping surfaces, there will be geometry errors because of floating point errors. So that explains your first four scenarios, where cylindrical surfaces overlap I believe.

The last two are are due to a problem with the logic in the code when a conestack is inscribed in an envelope (again the root cause is floating-point error), when the particle is near a "corner" between two layers in the cone stack. We made some progress in fixing this bug a while ago, but it still is not completely robust.

For the time being, you can avoid the problem by padding extra layers in your conestack so that from the outside it appears as a cylinder, for example:
```
:start layer:
    thickness    = 1
    top radii    = 1
    bottom radii = 1
    media        = H2O
:stop layer:

:start layer:
    thickness    = 1
    top radii    = 0.5 1          # extra padding radius to 1 cm to match radius of previous layer
    bottom radii = 0.5 1          # extra padding layer to 1 cm to match radius of previous layer
    media        = H2O H2O
:stop layer:
```

**Comment by mchamberland** [comment]
Thanks for the workaround! It's not perfect, but it works in a pinch. Hopefully, my simple input file at least provides something to test any improvements to the cone stack code against.
