### ISSUE TITLE
Syntax error in HEN_HOUSE/scripts/configure

### ISSUE THREAD

**Issue by marenaud** [nrc-cnrc/EGSnrc#3]
Hello!
There's a syntax error on line 271 of HEN_HOUSE/scripts/configure:
    for test_file in $((ls conftest.o conftest.obj; ls conftest.*) 2>/dev/null); do

Probably meant to write
    for test_file in $(ls conftest.o conftest.obj 2>/dev/null;
                ls conftest.* 2>/dev/null); do

(at least that works on my machine... modelled after line 296)

**Comment by ftessier** [comment]
Interesting: I can't reproduce the syntax error. What OS and bash version are you running on?

**Comment by marenaud** [comment]
Xubuntu 14.04 et Ubuntu 14.04,
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)

Here's the log (the specific line number is not helpful since it's looking for a closing bracket and never finding it):

You can exit this script at any time by typing Ctrl-C.

Press enter to continue.

Checking system type ...                          x86_64-unknown-linux-gnu
Checking for make ...                             yes (/usr/bin/make)

Looking for installed fortran compilers ...       OK

Found the following FORTRAN compilers in your search path:
    gfortran f95

Input fortran compiler:                           [gfortran]
Testing if gfortran works ...                     ./configure: 2659: ./configure: Syntax error: Missing '))'

**Comment by ftessier** [comment]
Thank you @marenaud. What is happening is that the `$((...) ...)` expression was meant as a shell command substitution `$(...)`, which itself contained a subshell (...) expression. The problem is that the leading `$((` string collides with the syntax for an arithmetic expansion! I removed the inside subshell expression, hence this becomes a non-issue. Otherwise the solution would have been to add a spaces around the inside shell expansion brackets, e.g., `$( (...) )`.

(Still not sure why the syntax error is not triggered for me here, under bash 4.3.29)
