### ISSUE TITLE
bremsstrahlung correction=NRC missing for RMISW521 in material.dat

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#348]
It seems that bremsstrahlung correction=NRC has been used for every material in material.dat file. Why RMISW521 is the only one where this option is missing?

**Comment by ftessier** [comment]
First order guess is that this is an oversight. @blakewalters can you comment? Did you know that `RMISW521` is a Googlewhackblatt?

**Comment by blakewalters** [comment]
This is because RMISW521 is the only material data in 521icru.pegs4dat that was generated using the old Koch and Motz correction to the bremsstrahlung cross section (IAPRIM=0) instead of the NRC correction (IAPRIM=1), and insofar as the media in material.dat are intended to replicate exactly those in 521icru.pegs4dat and 700icru.pegs4dat, hey...

**Comment by ojalaj** [comment]
OK.
