### ISSUE TITLE
Ivalue, aluminium alloy

### ISSUE THREAD

**Issue by bourgouina** [nrc-cnrc/EGSnrc#573]
In the file:
EGSnrc/HEN_HOUSE/pegs4/density_corrections/compounds/aluminumalloy_type6061.density

The I-value is 188.02901 eV while is should be something close to pure aluminum I-value of 166 eV.
NIST ESTAR program issue

**Comment by ftessier** [comment]
This is correct, the ICRU Report 90 clearly states that the mean excitation energy (I-value) of aluminum is one of the best known, an reiterates: `I_Al = 166 eV` with a standard uncertainty `1.3 eV`. Since aluminum type 6061 contains only about 2% impurities (mostly Mg and Si, around Al), it makes sense to use 166 ev as the I-value in `aluminumalloy_type6061.density`, unless `estar` can calculate a close value. I will review the other aluminum density correction files and open a pull request to fix this.

**Comment by ftessier** [comment]
Same argument applies for `aluminumalloy_type1100.density`. More hesitant with `aluminumalloy_type2014.density` which has 4% copper. @mainegra `estar` balks on trying to run with the `aluminumoxide1.0gcm3.density` data input, are you able to check it at your end?

**Comment by ftessier** [comment]
The problem with `estar` was that I had to input Element symbols as `Mg` instead of `MG` (!). I recomputed the aluminum alloy density corrections with `estar` (icru90 version) and I get I-values very close to pure aluminum (166 eV), which makes more sense.

**Comment by ftessier** [comment]
Comments continued in pull request #705.
