### ISSUE TITLE
Installation issues in a cluster

### ISSUE THREAD

**Issue by drqrius** [nrc-cnrc/EGSnrc#616]
Hello,

I have successfully installed EGSnrc in many computers, but I am having problems installing the 2018 version in a cluster whilst it installs well in the workstation.

I went through other issues and the reddit comments, but I haven't managed to fix it. It seems to be a problem with the mortran compilation, and the first issue appears when checking the record length, and variables sizes are replaced by 'fixme!'?  In a recent issue, it is suggested that newer fortran compilers can result in errors, but I am running version 7.3. Other issue mentioned '@' symbols within paths for cluster accounts being a problem, but it's not that either. Any suggestions?

I used the configure script for installation and this is the log:

[configure-cluster.log](https://github.com/nrc-cnrc/EGSnrc/files/5001539/configure-cluster.log)

Thanks,
Ana

**Comment by rtownson** [comment]
I haven't seen this issue before. It is possible that it's related to the fortran version. You could try hard-coding a record length (though I would expect this isn't the only issue). E.g. in `HEN_HOUSE/scripts/configure` line 2119 replace:
```
REPLACE {\$RECL-FACTOR} WITH {'fixme!'}
```
with
```
REPLACE {\$RECL-FACTOR} WITH {4}
```
and then run the configure script again. Note that this will not effect the installer GUI. It would be more difficult to make the change in the GUI.

**Comment by drqrius** [comment]
Thanks! That seemed to fixed part of the problem. I just use the EGS++ side of the code and the only time I use the GUI is to create pegs files which I can do on the workstation and then transfer them to the cluster, so I could ok with that. However, when I run my egs++ user code, I now get this error:

```
Reading NRC pair data base from /home/amdb/EGSnrc-2018/HEN_HOUSE/data/pair_nrc1.data

Data generated on a machine with 1234 endianess
The endianess of this CPU is xxxx
=> will need to do byte swaping
Energy range of the data: *********    0.301

***************** Error: 
 Inconsistent x-grid size

***************** Quiting now.
```

It looks like the 'Inconistent x-grid size' error also comes from the mortran code so it's probably related to the same issue.

**Comment by rtownson** [comment]
I just meant that the installer GUI wouldn't apply that change, so you had to use the configure script. The other GUIs should work as usual.

This error means that the endianess couldn't be determined during the installation, which we could again hard-code. I am concerned to continue fixing it that way though, since there could be further issues that go unnoticed. Though it's up to you - it's line 1215 where you could change xxxx to 1234. Are you able to try a different fortran version?

**Comment by drqrius** [comment]
Ok, I see what you mean about the GUIs. You are right, it's probably a bit dangerous to start hard coding too many things. I will ask whether it is possible to get a different fortran installed in the cluster. Unless you have any particular suggestion, I will try 7.5, which is what I am currently running in the pc.

Thanks again. I will report back if that fixes it.

**Comment by FredericBrochu** [comment]
I had a look at Ana's issues with compiling on our cluster and found that the configure script failed to report the correct record length because the linux command:
junk_size=$(ls -al junk_file | awk '{print $5}')
in line 1198 did not report the file size as expected, but the second part of the group name (yes, we have a pretty peculiar setup, with a long group name containing a white space)
Replacing the above with:
junk_size=$(stat -c '%s' junk_file) 
did the trick and let beamdp compile on our cluster.
Best regards.
                                  Frederic

**Comment by drqrius** [comment]
I can confirm that Frederic's suggestion fixes the installation issues and I can also compile my EGS++ user code without problems.

**Comment by rtownson** [comment]
Thanks for posting your solution, and I'm glad you got it sorted out! I will mark this as a bug to be fixed.
