### ISSUE TITLE
Radiative Compton corrections warning in .egslog, but not in .egslst

### ISSUE THREAD

**Issue by ojalaj** [nrc-cnrc/EGSnrc#64]
I've enabled radiative compton corrections as instructed in the manuals. When performing a DOSXYZnrc run, a following warning is printed in `.egslog` file:
```
 Bound Compton scattering                                    ON
***************** Warning:
 You are trying to use radiative Compton corrections
 without having included rad_compton.mortran
 Radiative Compton corrections                               ON
 Rayleigh scattering                                         ON
```
but not in `.egslst file`. However, it is `rad_compton1.mortran` that I've included in the `Makefile`, not `rad_compton.mortran`. Which one is correct and is it running correctly? For accelerator models, is `sources.make` the correct file to add the line?

**Comment by mainegra** [comment]
Hi @ojalaj, you need to add `$(EGS_SOURCEDIR)rad_compton1.mortran` just before $(EGS_SOURCEDIR)get_inputs.mortran in your Makefile to void the macro $RADC_WARNING which issues the warning message you are seen and also sets radc_flag to 0. The warning message has a typo since it refers to `rad_compton.mortran` when it should be `rad_compton1.mortran`. I realize that the EGSnrc manual states that `$(EGS_SOURCEDIR)rad_compton1.mortran` should be added just before `$(EGS_SOURCEDIR)egsnrc.mortran`. _This of course should be corrected._ The reason for implementing it this way was as safety measure to make sure that one did not forget to add the source file for radiative Compton corrections while requesting the corrections via the input file.
