### ISSUE TITLE
A question: how can I flag the secondary electrons

### ISSUE THREAD

**Issue by BINDX93** [nrc-cnrc/EGSnrc#655]
Dear experts,
I'm an EGSnrc beginner. 
There is a cavity chamber irradiated by a parallel photon beam.
And I would like to ask how can I flag the secondary electrons caused by photon interactions in the cavity. And how can I calculate the energy deposited by the secondary electrons? Thanks a lot. 
<img width="2046" alt="1" src="https://user-images.githubusercontent.com/53430658/102976996-5d906d80-453d-11eb-9a85-556a5ab7094c.png">

**Comment by rtownson** [comment]
Did you find an answer to this question? There is no simple input file option to do this at the moment, it requires a bit of c++ coding in cavity itself.

**Comment by BINDX93** [comment]
> Did you find an answer to this question? There is no simple input file option to do this at the moment, it requires a bit of c++ coding in cavity itself.
> 
> Here is a somewhat related conversation: https://www.reddit.com/r/EGSnrc/comments/jyczsq/how_to_output_only_the_primary_electrons/

Dear sir, I haven't figured out this problem. Thanks for your reply.

**Comment by rtownson** [comment]
You'll want to look in the `ausgab()` routine of cavity, and find instances of `dose->score(`. This is when dose is being recorded. If you put an `if` statement around that, you could check the charge of the particle to score only dose from electrons, e.g. `if(the_stack->q[np] < 0)`. This is off the top of my head, but seems to come close to what you're looking for. If you want energy instead of dose, comment out line 1225 and use line 1226 instead.

**Comment by rtownson** [comment]
I'm closing this issue for now. If you have more questions about this, consider asking them on our [reddit page](https://www.reddit.com/r/EGSnrc/) - you might get a faster response!
