### ISSUE TITLE
error for source 19 angular distribution in BEAMnrc

### ISSUE THREAD

**Issue by jantolak** [nrc-cnrc/EGSnrc#656]
In beamnrc.mortran, line 11954, there is an error in sampling the angular distribution.
<pre>
    IF( sigma_src19 > 0 ) [
      "find uin,vin,win if there is angular spread"
        LOOP [
            $RANDOMSET win; win = 1 + sigma_src19*log(1-win);
        ] UNTIL (win > 0);
        uin = sqrt((1-win)*(1+win));
        $RANDOMSET PHI; PHI = 6.283185308*PHI;
        vin = uin*sin(phi); uin = uin*cos(phi);
</pre>
The initial loop is trying to make sure that u^2+v^2 < 1, but it actually is making sure that u^2+v^2 < 2. If you look at the code for sample the spatial distribution, where it says *ZIN really radius*, there is a factor of 2 there that did not make it into the angular sampling. Another error is made when calculating uin (and it partially compensates for the previous error). If you do the math inside the square root, you get -2*sigma_src19*log(1-win) minus another term that is incorrect (just compare to the spatial sampling).

Here is my suggestion for correcting this code.
<pre>
    IF( sigma_src19 > 0 ) [
      "find uin,vin,win if there is angular spread"
        LOOP [
            $RANDOMSET win; win = 1 + 2*sigma_src19*log(1-win);
        ] UNTIL (win > 0);
        uin = sqrt(1-win);
        $RANDOMSET PHI; PHI = 6.283185308*PHI;
        vin = uin*sin(phi); uin = uin*cos(phi);
</pre>
It could be simplified even further by realizing that the loop is not really needed. You can calculate the maximum random number that will satisfy the loop as 1 &minus; exp(-0.5/sigma_src19).
<pre>
    IF( sigma_src19 > 0 ) [
      "find uin,vin,win if there is angular spread"
        $RANDOMSET win;
        win = win*0.999*(1 - exp(-0.5/sigma_src19));
        win = 1 + 2*sigma_src19*log(1-win);
        uin = sqrt(1-win);
        $RANDOMSET PHI; PHI = 6.283185308*PHI;
        vin = uin*sin(phi); uin = uin*cos(phi);
</pre>
I added the 0.999 factor to make sure that the sampled random number does not lead to an accidental negative square root a couple of lines down. It would probably be good to pre-calculate the upper limit on the allowable random numbers instead of calculating the exponential over and over.

**Comment by blakewalters** [comment]
Hi @jantolak:  And Happy New Year!  How're things going?  And thanks for the detailed look at the code!  

Are you seeing evidence of an issue with the incident angular distribution when sigma_src19>0?  Because after looking through the code, I don't see an issue with the angular sampling.  We're using the small angle approximation for the incident cosine of the angle with respect to the Z-axis, win.  So,

win ~ 1 - theta^2/2, where theta is the particle angle wrt the Z-axis (rad).

If theta has a gaussian distribution with standard deviation, sig_theta, then:

$RANDOMSET win;
win = 1 - [sig_theta*sqrt(-2ln(1-win))]^2/2
       = 1 + sig_theta^2*ln(1-win)

At this point in the code, sigma_src19 actually carries sig_theta^2 (see line ~10255) and so:

win = 1 + sigma_src19*ln(1-win)

This gives us our value of win, but then we need to randomly sample incident X- and Y- direction cosines, uin and vin, assuming an even distribution of incident positions over 2pi in the X-Y plane.  This is done by first determining a value of uin that assumes the particle is incident in the X-Z plane:

uin = sqrt(1-win^2)
   = sqrt((1-win)(1+win))

and then applying a random rotation evenly distributed over 2pi in the X-Y plane to this value to get the final values of uin and vin.

I agree that the loop check on win > 0 is unnecessary provided that we impose a maximum value on win sampled from the uniform random distribution, i.e.

$RANDOMSET win;
win = win*0.999*(1-exp(-1/sigma_src19));
...

Please take a look at the above and let me know if this doesn't make sense or if you think there's a mistake in the logic.  Thanks!

**Comment by jantolak** [comment]
Thanks for clarifying, @blakewalters. I'm doing well and hope you are too.

I now see what the code is doing (it is OK), and I also see that my solution was incomplete. Your code is actually sampling w, using a Gaussian distribution for theta. I mistakenly assumed that "win" was being used as a temporary variable to sample u and v, which are the real random variables (in my opinion). Here is my logic (I'm going to use u,v,w).

We know that u<sup>2</sup> &plus; v<sup>2</sup> &plus; w<sup>2</sup> &equals; 1. We also know that w = cos(&theta;), so u<sup>2</sup> &plus; v<sup>2</sup> &equals; sin<sup>2</sup>(&theta;). The distribution in x and y directions should be independent (much like the joint Gaussian distribution for the spatial spread). The u component of the direction vector is u &equals; sin(&theta;<sub>x</sub>) and v &equals; sin(&theta;<sub>y</sub>). Both &theta;<sub>x</sub> and &theta;<sub>y</sub> should have a Gaussian distribution. Using a small angle approximation, u &equals; &theta;<sub>x</sub> and u &equals; &theta;<sub>y</sub>. The distribution of u<sup>2</sup> &plus; v<sup>2</sup> is exactly like the distribution of x<sup>2</sup> &plus; y<sup>2</sup> when sampling Gaussian spatial distribution, so I was sampling u and v from the joint Gaussian distribution and then forgot to calculate w &equals; sqrt(1 &minus; (u<sup>2</sup> &plus; v<sup>2</sup>)).

There is also a partial ambiguity with respect to specifying the sigma. When sampling the spatial distribution, you are saying that you have a &sigma;<sub>x</sub> and &sigma;<sub>y</sub>. The variance in the radial direction is double the variance in the x or y directions (2&sigma;<sup>2</sup><sub>x</sub> &equals; &sigma;<sup>2</sup><sub>r</sub>), which is the factor of 2 in my solution, so I was assuming that the input file was specifying &sigma;<sub>u</sub> and the current source code assumes it is sqrt(2) times that. My proposed code used "win" as a temporary variable (like the R in the spatial sampling), so there needs to be an extra line that computes w.

I agree that your code now makes sense, although sampling w first was confusing to me (u and v are really the random variables in my opinion). This is my corrected code that would do almost the same thing.

    IF( sigma_src19 > 0 ) [
      "find uin,vin,win if there is angular spread"
        $RANDOMSET uin;
        "make sure u^2+v^2 < 1"
        uin = uin*0.999*(1 - exp(-1/sigma_src19));
        uin = -LOG(1-uin); "uin is really u^2+v^2"
        win = sqrt(1-uin);
        $RANDOMSET PHI; PHI = 6.283185308*PHI;
        vin = sqrt(uin)*sin(phi); uin = sqrt(uin)*cos(phi);

I'll have to  check my math (later) to make sure the result is the same, or at least within approximation (small angle) error.

**Comment by blakewalters** [comment]
I think I see where the confusion arose, @jantolak:  Yes, we're going straight to the calculation of w from a gaussian distribution of angle wrt the Z-axis (specified by sigma_src19) and then calculating u and v instead of starting from a gaussian distribution of theta_x and theta_y and doing it the other way round.  I admit that having the same variable, win, store the random number and, ultimately, the value of w doesn't exactly make code interpretation easier.

**Comment by jantolak** [comment]
Not sure if this is appropriate for me to do, but I'll just close this.
