### ISSUE TITLE
egs++ phsp scoring bug when scoring plane intersects regions

### ISSUE THREAD

**Issue by rtownson** [nrc-cnrc/EGSnrc#876]
It seems that particles are scored incorrectly for egs++ phsp scoring when the scoring plane intersects more than one region. I reproduced the issue both for egsphsp and IAEA (constant Z) formats.

See issue and example input file here: https://www.reddit.com/r/EGSnrc/comments/uxvu5b/issues_with_scoreplane/

**Comment by Elhamvahebi** [comment]
Hello sir 
I'm Elham vahebi of Tehran university in Iran.
I put a plan TBI and opened a 40 x 40
percent field. Because the patient is TBI, I
put it in ssd 200, and the field size is about
80 × 80. But when we irradiate the
phantom with the same conditions,
unfortunately the phantom does not take a
dose. Shows only green and blue doses, ie
50% doses. And does not show high doses
and 100% doses. I do not know exactly
where I am wrong and what circumstances
I have not considered. Please help me or
introduce me to someone to help me.
thanks a lot

**Comment by blakewalters** [comment]
@rtownson:  I finally had a chance to look at this issue posted to reddit > 1 yr ago (!).  The documentation for egs_phsp_scoring states (maybe not clearly enough) that when using the "phase space geometry" method, scoring surfaces must coincide with region boundaries.  Considering this then, if I move the scoring plane, "flatPanel", from Z=5.002 cm to Z=5.0019 cm, I get a photon X-Y distribution that looks more reasonable.  There can, indeed, be roundoff issues when attempting to match a "phase space geometry" to a region boundary that can then lead to erroneous particle scoring, but I don't think that's what's happening here.

**Comment by blakewalters** [comment]
@rtownson, @ftessier: I think we can close this issue.  See my comment above.

**Comment by ftessier** [comment]
@rtownson your get the OP privilege of closing the issue! 😉
